Extract check for unique directive names into separate rule
webonyx/graphql-php pull request #1109
Opened 2022-04-18 08:00 UTC by vhenzl

Introduces `UniqueDirectiveNames` validation rule.

Corresponding change in the reference implementation: https://github.com/graphql/graphql-js/commit/c1745228b2ae5ec89b8de36ea766d544607e21ea

2022-04-19 07:39 UTC, spawnia requested changes

2022-04-19 07:39 UTC, spawnia commented on src/Validator/Rules/UniqueDirectiveNames.php
> +declare(strict_types=1);
```suggestion
<?php declare(strict_types=1);
```

2022-04-19 07:39 UTC, spawnia commented on tests/Validator/UniqueDirectiveNamesTest.php
> +declare(strict_types=1);
```suggestion
<?php declare(strict_types=1);
```

2022-04-22 09:15 UTC, vhenzl commented
This should be good now.

2022-04-22 13:10 UTC, spawnia approved these changes

2022-04-22 13:10 UTC, merged