add example with reactphp
webonyx/graphql-php pull request #1181
Opened 2022-06-17 15:01 UTC by Chrisdowson

2022-06-23 07:14 UTC, spawnia commented
Static analysis fails: https://github.com/webonyx/graphql-php/runs/7018012660?check_suite_focus=true

2022-06-23 08:33 UTC, spawnia commented
Try running static analysis locally, see https://github.com/webonyx/graphql-php/blob/master/CONTRIBUTING.md#static-analysis

2022-06-24 13:27 UTC, spawnia requested changes

2022-06-24 13:27 UTC, spawnia commented on composer.json
> +    "react/http": "^1.6"
Should be in require-dev

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/README.md
> +This is a Simple yet full-featured example with reactphp.
```suggestion
This is a basic example using [ReactPHP](https://reactphp.org).
```

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +    $queryType = new ObjectType([
This and the following code should not be indented

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +                    $deferred = new \React\Promise\Deferred();
use imports

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +                    });
```suggestion
                    $promise = $promise->then(static fn (): string => $rootValue['prefix'] . $args['message']);
```

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +    $server = new \React\Http\HttpServer(function (Psr\Http\Message\ServerRequestInterface $request) use ($schema, $react) {
Return type?

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +                (json_encode($output) !== false) ? json_encode($output) : ''
This encodes twice, very inefficient

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +            $output = $result->toArray(1);
Use constants over magic values

2022-06-24 13:27 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +    echo 'Listening on ' . str_replace('tcp:', 'http:', $socket->getAddress() ?? '') . PHP_EOL;
Why the fallback? When can this be `null`?

2022-11-10 13:42 UTC, spawnia commented on examples/04-hello-world-with-reactphp/graphql.php
> +        $output = json_encode($result->toArray(1));
Still using a magic value, there is a constant for this

2022-11-10 15:53 UTC, closed without merging

2022-11-11 10:50 UTC, spawnia commented
@Chrisdowson I was willing to include this example with a few minor tweaks, if you are still up for it.

2022-11-11 15:31 UTC, Chrisdowson commented
> @Chrisdowson I was willing to include this example with a few minor tweaks, if you are still up for it.
of course,It's my pleasure

2022-11-11 15:35 UTC, Chrisdowson commented
@spawnia of course, It's my pleasure