Add methods for properties in interface `NamedType`
webonyx/graphql-php pull request #1253
Opened 2022-12-06 12:39 UTC by simPod

Since dynamic properties are to be removed in PHP 9, we should start working on replacing them.

E.g. this https://github.com/webonyx/graphql-php/pull/1252 is not really sufficient either as graphql-php now gives mixed errors on dynamic properties to consumers.

Also, `AllowDynamicProperties` attribute is supported only on classes, not interfaces.

--------

I have implemented basic getters for `NamedType` as an example how it should look in the future. WDYT?

2022-12-06 12:43 UTC, spawnia commented
We are not actually using dynamic properties anywhere.

2022-12-06 13:00 UTC, simPod commented
Hm, I see. BTW how do you access `name` of `NamedType` in consumer libs? PHPStan does not see those props there on 8.2.

2022-12-06 13:32 UTC, spawnia commented
Well currently we and others have to ignore the PHPStan errors.

I defnitely see your point, introducing methods would definitely be one way of making this problem go away. Unfortunately we can not have properties on interfaces - or something like sealed interfaces / union types.

2022-12-06 14:09 UTC, simPod commented
Sure. So what about this POC introducing interface contracts that would allow consumers to call methods?

2022-12-06 14:21 UTC, spawnia commented
I am fine with this.

2022-12-07 09:37 UTC, spawnia requested changes
The return types of `astNode` and `extensionASTNodes` should be more precise in implementations - otherwise consumers are going to add unnecessary checks or assertions.

2022-12-07 09:37 UTC, spawnia commented on tests/Type/DefinitionTest.php
> +        $description = 'To the quartered rhubarb add lobster, lettuce, eggs sauce and bitter strudel.';
Nice

2022-12-07 10:31 UTC, simPod commented on src/Type/Definition/InputObjectType.php
> +    public function astNode(): ?Node
Good point

2022-12-07 10:37 UTC, merged