Adding more async examples (with AMPHP)
webonyx/graphql-php pull request #1349
Opened 2023-03-17 10:44 UTC by kinimodmeyer

- Mentioning in the documentation also the existing AMPHP adapter `AmpPromiseAdapter`
- Adding two more async examples for amphp.
   - One which is similar to the existing reactphp example (http server)
   - Another one which can be run in environments with php fpm/apache
- Remove icicle.io from the list (is long ago deprecated in favor of Amp v2.0)
- Remove notice regarding version 0.9.0. seems long outdated as we are at version v15

In general AMPHP (& ReactPHP) reworking their frameworks to work natively with PHP8.1 fibers.
With new AMPv3 we might not need the "call" anymore. I´m unsure if the adaper might need a change too.
In a next iteration i will test this.

2023-03-17 11:34 UTC, spawnia reviewed
Thanks for adding this, I like the direction

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/README.md
> +While you can create an own http-server with PHP GraphQL & AMPHP (see "http-server" example)
```suggestion
While you can create your own http-server with PHP GraphQL & AMPHP (see "http-server" example),
```

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/README.md
> +this example aims to give you an event-loop on traditional request model (apache, fpm, ...)
```suggestion
this example aims to give you an event-loop combined with the traditional request model (apache, fpm, ...).
```

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/graphql.php
> +\Amp\Loop::run(function () use ($schema) {
import

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/graphql.php
> +\Amp\Loop::run(function () use ($schema) {
return type?

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/graphql.php
> +    $promise->then(function(ExecutionResult $result) use (&$resultArray) {
void

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/event-loop/graphql.php
> +    echo json_encode($resultArray);
why not echo in `then()`?

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +\Amp\Loop::run(function () use ($schema) {
import + return type

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +        Amp\Socket\Server::listen("localhost:8080"),
import

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +    $server = new HttpServer($sockets, new CallableRequestHandler(function (Request $request) use ($schema) {
retuurn type?

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +            return new Response(
short closure + return type

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/schema.php
> +    'query' => new GraphQL\Type\Definition\ObjectType([
use imports

2023-03-17 11:34 UTC, spawnia commented on examples/04-async-php/amphp/schema.php
> +                        function() {
short closure + type

2023-03-18 10:13 UTC, kinimodmeyer commented
@spawnia thanks for the fast review, i modified it regardless your valid suggestions.

Regarding the psalm errors, are you fine by adding "amp/http-server" to composer require-dev? (& suggest)
(should not make a lot dependencies as we have amp framework already)

Or do you want to modify psalm for the examples/* directories?
(then we **could** remove react/http|promise dependency too)

2023-03-19 18:56 UTC, spawnia requested changes

2023-03-19 18:56 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +                $data !== false ? $data : null
Use `JSON_THROW_ON_ERROR` instead (in every `json_encode()` example)

2023-03-19 18:56 UTC, spawnia commented on examples/04-async-php/amphp/http-server/graphql.php
> +    }), new Psr\Log\NullLogger);
import

2023-03-19 18:56 UTC, spawnia commented on examples/04-async-php/amphp/schema.php
> +                    return call(
can be a short closure

2023-03-19 18:56 UTC, spawnia commented on examples/04-async-php/amphp/schema.php
> + * The article/product resolver get now resolved asynchronous.
```suggestion
 * The resolvers for "product" and "article" resolver run asynchronously.
```

2023-03-19 18:56 UTC, spawnia commented on examples/04-async-php/amphp/schema.php
> + * Keep in mind, everything in "call" should now be non-blocking, checkout out async libraries like (amphp/mysql, amphp/http-client).
```suggestion
 * Keep in mind everything in "call" should be non-blocking, check out async libraries like amphp/mysql, amphp/http-client.
```

2023-03-20 08:37 UTC, merged